### PR TITLE
correcting rubin-falcone23a

### PR DESCRIPTION
**Pull request by bobakm**
correcting rubin-falcone23a with updated acknowledgements section

### CODE REVIEW

**Comment by bobakm** [comment]
also adding update to la-cava23a.pdf

**Comment by lacava** [comment]
hey @bobakm, I believe this PR would also correct [my manuscript](https:/proceedings.mlr.press/v209/la-cava23a.html) via commit 7ec0452 . will it be merged soon? thanks

**Review by lawrennd — CHANGES_REQUESTED** [review]
Apologies for delay on this. @Bobak, there seem to be 2 new pdfs one with a misspelling, for the Rubin-Falcone paper. can we remove one?

**Comment by bobakm** [comment]
Yes @lawrennd we can remove the one with the misspelling!

**Comment by lawrennd** [comment]
Great, could you resubmit the pull request with it removed? (I think I can't easily do that).

**Pull request closed without merging**
